feat: allow servcies to return data
Digital-Alchemy-TS/hass pull request #65
Opened 2024-09-09 00:50 UTC by allout58

## 📬 Changes

Fixes #34

TODOs:
 - [ ] Add Unit Tests
 - [ ] Update documentation to remove warning aboue #34 
 - [ ] Prevent (or just warn like previous code warning about #34 was) when trying to use it with the REST API rather than the WebSocket API
    -  See https://github.com/home-assistant/core/issues/106379#issuecomment-1878548124

## 🗒️ Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the
  [code](../CODE_OF_CONDUCT.md) of conduct
- [ ] Readme and [docs](https://docs.digital-alchemy.app/) (updated or not needed)
- [ ] Tests (added, updated or not needed)

2024-09-09 03:03 UTC, zoe-codez requested changes

2024-09-09 03:03 UTC, zoe-codez commented on src/helpers/fetch/weather-forecasts.ts
> +   * The temperature in the unit indicated by the <code>temperature_unite</code> state attribute. If <code>templow</code> is also provided this is the higher temperature.
Editor eats html stuff like this 😢 

![2024-09-08_22-01](https://github.com/user-attachments/assets/39eab332-0158-4ff9-82c0-fe236fc02e70)

2024-09-10 00:36 UTC, allout58 commented on src/helpers/fetch/weather-forecasts.ts
> +   * The temperature in the unit indicated by the <code>temperature_unite</code> state attribute. If <code>templow</code> is also provided this is the higher temperature.
Seems like VSCode at least is happy with the markdown inline code single backtick, so that's what I went with. Even if an editor doesn't do anything with the markdown, it shouldn't eat it like `<code>bla</code>` was

2024-09-10 01:19 UTC, zoe-codez approved these changes

2024-09-10 01:34 UTC, merged